version: '3.8'

services:
  account-api:
    container_name: account-api
    build:
      context: .
      dockerfile: Inno_Shop.AccountApi/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
  
  product-api:
    container_name: product-api
    build:
      context: .
      dockerfile: Inno_Shop.ProductApi/Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - db

  db:
    container_name: db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - db-data:/var/opt/mssql

volumes:
  db-data:
